#comment: This Dockerfile is used to create a simple container that serves HTTP content
#comment: It uses the official HTTPD image as the base
#comment: The container will expose port 80 for HTTP traffic
#comment: This is an example of a basic web server setup
#comment: The EXPOSE instruction indicates the port on which the container listens for connections

FROM httpd:2.4

EXPOSE 80
